//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personnel
    {
        public int ID { get; set; }

        [Display(Name = "Departman Adi")]
        [Required(ErrorMessage ="Departmanýn ad bilgisi zorunludur!")]
        public int DepartmentId { get; set; }

        [Display(Name = "Ad")]
        [Required(ErrorMessage = "Personelin ad bilgisi zorunludur!")]
        [MaxLength(50, ErrorMessage = "Ad bilgisi 50 karakterden fazla olamaz!")]
        public string Name { get; set; }

        [Display(Name = "Soyad")]
        [Required(ErrorMessage = "Personelin soyad bilgisi zorunludur!")]
        [MaxLength(50, ErrorMessage = "Soyad bilgisi 50 karakterden fazla olamaz!")]
        public string Surname { get; set; }

        [Display(Name = "Maaþ")]
        [Required(ErrorMessage = "Personelin maaþ bilgisi zorunludur!")]
        [Range(4449, 20000, ErrorMessage ="Maaþ 4.500 Lira ile 20.000 Lira arasýnda olmalýdýr.")]
        public Nullable<int> Salary { get; set; }

        [Display(Name = "Doðum Tarihi")]
        [Required(ErrorMessage = "Personelin doðum tarihi bilgisi zorunludur!")]
        public Nullable<System.DateTime> Birthday { get; set; }

        [Display(Name = "Cinsiyet")]
        [Required(ErrorMessage = "Personelin cinsiyet bilgisi zorunludur!")]
        public Nullable<bool> Gender { get; set; }

        [Display(Name = "Medeni Hal")]
        public bool IsMarried { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
